services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: SQLServer2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd.
      MSSQL_PID: Express
    volumes:
      - C:\Users\a842225\source\repos\GitJoshua\WebBackEndRepo\DB\data:/var/opt/mssql/data
      - C:\Users\a842225\source\repos\GitJoshua\WebBackEndRepo\DB\secrets:/var/opt/mssql/secrets
      - C:\Users\a842225\source\repos\GitJoshua\WebBackEndRepo\DB\log:/var/opt/mssql/log